# Generated by Django 6.0.1 on 2026-02-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
    ]
