# Generated by Django 6.0.1 on 2026-02-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_event_end_datetime_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
