# Generated by Django 6.0.1 on 2026-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
