# Generated by Django 6.0.1 on 2026-03-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_event_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='event',
            name='seats_per_row',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.seat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tickets.event'),
        ),
    ]
