# Generated by Django 6.0.1 on 2026-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_seat_is_booked_remove_ticket_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_seats',
        ),
    ]
