# Generated by Django 6.0.1 on 2026-03-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_eventpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_end_row',
            field=models.CharField(default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_start_row',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
