# Generated by Django 6.0.1 on 2026-03-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_event_discount_end_event_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='vip_end_row',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_start_row',
        ),
        migrations.AddField(
            model_name='event',
            name='vip_row_end',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_row_start',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
