# Generated by Django 6.0.1 on 2026-03-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_event_vip_end_row_remove_event_vip_start_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='ticket_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('VIP', 'VIP')], default='Standard', max_length=10),
        ),
    ]
