# Generated by Django 6.0.1 on 2026-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_seat_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='columns',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='rows',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='seating_design',
            field=models.CharField(choices=[('theatre', 'Lecture Theatre (Cinema Style)'), ('middle_path', 'Left & Right with Middle Path'), ('top_bottom', 'Top and Bottom Seating'), ('arena', 'Seats Around Stage'), ('matrix', 'Normal Matrix Seating'), ('no_seats', 'No Seats Event')], default='matrix', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
