# Generated by Django 6.0.1 on 2026-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_event_columns_event_rows_event_seating_design_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_per_location_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='discount_end',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='seating_design',
            field=models.CharField(choices=[('cinema', 'Cinema / Lecture Theatre'), ('grid', 'Cinema Grid'), ('arena', 'Stadium Arena'), ('vip_front', 'VIP Front Rows')], default='cinema', max_length=20),
        ),
        migrations.RemoveField(
            model_name='event',
            name='seats_per_row',
        ),
    ]
