# Generated by Django 6.0.1 on 2026-03-15 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_remove_event_unique_event_per_location_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seating_design',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_row_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_row_start',
        ),
        migrations.AddField(
            model_name='event',
            name='seats_per_row',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
