# Generated by Django 6.0.1 on 2026-03-16 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_event_seating_design_remove_event_vip_row_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventPriceHistory',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
