# Generated by Django 6.0.1 on 2026-03-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_remove_studentprofile_user_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default='Standard', max_length=10),
            preserve_default=False,
        ),
    ]
